application: reg-sys
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /words\.txt
  static_files: words.txt
  upload: /words\.txt
  
- url: /static
  static_dir: static
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
